### ISSUE TITLE
Cannot find Amazon community instance

### ISSUE THREAD

**Issue by Strangemother** [commonsense/conceptnet5#157]
I want to boot my own instance, but I cannot find `conceptnet-5.5.5` or anything similar in the EC2 community AMI list.

Could you point me in the right direction?

Thanks in advance

**Comment by rspeer** [comment]
I just confirmed that I can find it by searching "conceptnet-5.5.5". The ID is `ami-99cec98f`.

**Comment by Strangemother** [comment]
Thank you for the quick response. When I perform that, I receive 1 result to an AWS Marketplace - connecting to a Lavel LAMP stack: https://aws.amazon.com/marketplace/pp/B073WWJ9BV?ref=cns_srchrow 

I know this is my fault, so I've attached a screenshot for sanity - What am I doing wrong?

![amazon-aws-conceptnet-search](https://user-images.githubusercontent.com/421660/36005723-e2679e90-0d30-11e8-9b75-a29a9aec5d4a.PNG)

**Comment by rspeer** [comment]
I looked into this. It appears to be an AWS bug that has affected other public images: https://forums.aws.amazon.com/thread.jspa?messageID=454676&#454676

There's no resolution to the bug, but I can try the bizarre workaround. (The problem is that the image shows up for _me_, so I won't know if it's fixed.)

**Comment by rspeer** [comment]
Oh! It's not due to this bug, it's because AMIs only exist in one region (something I didn't know until reading why people encountered the bug).

The ConceptNet AMI is in the `us-east-1` region, so that's where you need to launch the instance. I believe you can then copy the resulting machine to `eu-west-1` if you want.

**Comment by Strangemother** [comment]
There it is `US East (M. Virginia)`! I had picked Ireland for no reason.

Thank you so much I sincerely appreciate your time.
