### ISSUE TITLE
The ConceptNet database has not been built. after followed all the instructions of Build-process page.

### ISSUE THREAD

**Issue by terU3760** [commonsense/conceptnet5#166]
I followed the Build-process on this page: https://github.com/commonsense/conceptnet5/wiki/Build-process.
When I started the web server by the command: python conceptnet_web/api.py  and input: http://127.0.0.1:8084/c/en/example in the web browser. I got the following error:

{
  "@context": [
    "http://api.conceptnet.io/ld/conceptnet5.5/context.ld.json",
    "http://api.conceptnet.io/ld/conceptnet5.5/pagination.ld.json"
  ],
  "error": {
    "details": "The ConceptNet database has not been built.",
    "status": 503
  }
}

And I found the conceptnet5 database has been set up. It contains 7 tables: edge_features, edge_sources, edges, node_prefixes, nodes, relations, sources.

Where is the cause? Thanks in advance!

**Comment by rspeer** [comment]
There's a setup step that we've neglected to describe in the non-Docker case (and don't worry, by now I prefer the non-Docker case too, but I wish there was _some_ good way to encapsulate all the setup that needs to be done).

The Web server needs to know how to find ConceptNet's files. The error message that comes up from not being able to find the files is a bit silly, because the database is there, what it can't find is the file that signals that the database is ready.

The best way to do this is with the `CONCEPTNET_DATA` environment variable.

I need to figure out how to make paths more sensible when I can't rely on something like Docker to configure everything globally to be the way it needs to be.

If you're running the API by running Python out of the `web` directory, here's how I suggest fixing it for now (from the web directory):

```sh
CONCEPTNET_DATA=$(realpath ../data) python conceptnet_web/api.py
```

**Comment by terU3760** [comment]
@rspeer Solved. Thank you!
