### ISSUE TITLE
Error in web build

### ISSUE THREAD

**Issue by Vyso** [commonsense/conceptnet5#179]
<img width="710" alt="screen shot 2018-03-24 at 9 26 13 am" src="https://user-images.githubusercontent.com/28525524/37860743-909da5aa-2f45-11e8-8085-884c89e74e3a.png">

Any idea why I get this import error?

<img width="1440" alt="screen shot 2018-03-24 at 9 28 56 am" src="https://user-images.githubusercontent.com/28525524/37860769-eecc525c-2f45-11e8-89db-b45882833dba.png">
<img width="1438" alt="screen shot 2018-03-24 at 9 29 20 am" src="https://user-images.githubusercontent.com/28525524/37860771-f21cf308-2f45-11e8-83b8-d341e162ffd5.png">

Those are the files in my web and conceptnet_web folders.

**Comment by rspeer** [comment]
From your description, I don't know what process you followed to set up ConceptNet. Please let me know what setup instructions you followed so I can see if there's a missing step.

The problem is that `conceptnet_web` is a separate package. It lives in the `web/` subdirectory of the repository, and you need to install it. I suggest changing directory to `web/` and running `pip install -e .`.
