### ISSUE TITLE
How can I compute all possible paths or shortest paths between two concepts

### ISSUE THREAD

**Issue by abaheti95** [commonsense/conceptnet5#216]
Hi,
Is there a way in the API to query for a paths between 2 Concepts? If this is not a direct feature can you give me some guidelines as to how can I achieve this?

Thanks

**Comment by rspeer** [comment]
This isn't really a ConceptNet issue, just a question.

The graph data is available from https://github.com/commonsense/conceptnet5/wiki/Downloads, and you can load it into any graph library you choose.

Finding shortest path is a graph search problem. You could use Dijkstra's algorithm, which runs in `O(|E| + |V| log |V|)` -- but in ConceptNet, both `|E|` and `|V|` are fairly large. This may be far too inefficient for your purposes, but you won't be able to do much better than Dijkstra without simplifying the problem.

That's why we don't particularly support searching for paths in ConceptNet. Instead, we learn vector embeddings of the nodes in ConceptNet, where nodes that have more and stronger paths between them will have higher dot products. You can experiment with the relatedness API (https://github.com/commonsense/conceptnet5/wiki/API#looking-up-related-terms) and see if it does what you need.
