### ISSUE TITLE
Internal Server Error Querying Relatedness (ec2 instance)

### ISSUE THREAD

**Issue by bhylak** [commonsense/conceptnet5#243]
I followed the instructions for launching my own ec2 instance.

I can query nodes just fine, but when I try to use the relatedness end point I get a 500 error.

**Comment by bhylak** [comment]
Just checking in -- is there anyone that could help with this?

**Comment by bhylak** [comment]
Unfortunately that did not seem to resolve the problem @rspeer 
<img width="1015" alt="screen shot 2018-12-12 at 9 36 35 am" src="https://user-images.githubusercontent.com/19956321/49876478-7f54a700-fdf1-11e8-8be4-c314ac90e801.png">

**Comment by rspeer** [comment]
Hm, then it's not the problem I thought it was. (And that's a relief, because I _thought_ I had put the HDF5 files in the disk image, but I was doubting myself.)

It should be possible to get the traceback. One place to look for it would be `journalctl -u conceptnet`, though that's all just web server logs for me.

You could also see the traceback by running a debug server. From the same directory, could you run:

```
python web/conceptnet_web/api.py
```

and then, in another shell:

```
curl http://localhost:8084/related/c/en/example
```

**Comment by bhylak** [comment]
Realized the image was on 5.6.2, but this endpoint was not available then. 

Fixed this with `pip install --upgrade conceptnet`
