### ISSUE TITLE
syntax error at 'hash'

### ISSUE THREAD

**Issue by yyHaker** [commonsense/conceptnet5#246]
Hi, I am trying to install conceptnet on my linux system using puppet, but when I run puppet-apply.sh, it have the following error,
![image](https://user-images.githubusercontent.com/18585628/50817399-a5bd2200-135e-11e9-8893-1719711f34fc.png)
What's wrong with it?

**Comment by rspeer** [comment]
Sounds like the wrong version of Puppet.

I wrote this configuration file for Puppet 3, the one that is already available as a package on Ubuntu 16.04. I know it's outdated, but the issue was, if Puppet is responsible for installing dependencies, and you depend on a newer version of Puppet, how do you get that newer version?
