### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by JohannaOm** [commonsense/conceptnet5#279]
Hello,
I have seen the "dockerignore" file in repository. But I could not find "Dockerfile" file.
Is there a Dockerfile and a yaml file for concepnet?

**Comment by rspeer** [comment]
No - we tried Docker and it didn't fit well with ConceptNet.

The problem is that loading the data into the database is an important step that can't happen at build time (because it would make the image too large and break all the tooling) and can't happen at run time (because then the container would take several hours to start), but those are the only "times" in Docker.

A Docker container could run the API or something, querying a ConceptNet database that already exists, but that's not too helpful. Setting up the database is the hard part.
