### ISSUE TITLE
Make it easier to add concepts to ConceptNet

### ISSUE THREAD

**Issue by amirouche** [commonsense/conceptnet5#61]
Conceptnet5 users are in dire need to be able extend the ConceptNet5 with their own data. It's should be easy and straitgh forward to do.

My proposition is to create a database library to do that work that mimic the REST API.

WDYT?

**Comment by rspeer** [comment]
The distinction that I think is important to make is that ConceptNet is designed to represent domain-general knowledge. Domain-specific knowledge has different properties, and you probably want to handle it differently in your machine learning instead of mixing it all into the same graph. And if 
 instead you have a good additional source of domain-general knowledge that fits well with what's in ConceptNet, then I think adding a new reader module to ConceptNet (possibly in a pull request so we can merge it in upstream) is still the right thing to do with it.

We've figured out how to get good results out of a combination of ConceptNet and domain-specific data, but it takes a lot more effort and more NLP tools, and solving this problem is basically what we built the company Luminoso on.

There *is* some new machine learning that Luminoso is going to release into ConceptNet soon, by the way; it's not exactly going to solve your problem but it may help solve something related to it.

**Comment by zephirefaith** [comment]
HI, I am just a noob trying to get into a similar domain. I was wondering if there are some widely used open-source ontology management systems that developers use for keeping track of domain-specific knowledge? I figured this being a relevant topic on a well maintained repository with experienced developers, might be a good place to get answers.

**Comment by amirouche** [comment]
Personal backlog clean-up.
