### ISSUE TITLE
Iberian Portuguese

### ISSUE THREAD

**Issue by jarodium** [commonsense/conceptnet5#66]
I would like to warn that, Portuguese is Brazilian Portuguese.
Please add support for Iberian Portuguese.

**Comment by rspeer** [comment]
I should ask what you specifically mean by "support". I don't believe there's any support lacking for Iberian Portuguese in the code.

Certainly the Portuguese content is mostly in Brazilian Portuguese, as two out of the three data sources for Portuguese are Brazilian projects. But, as I look up vocabulary differences between Brazilian and Iberian Portuguese, it seems that the Iberian words are also represented in ConceptNet:

* http://conceptnet5.media.mit.edu/web/c/pt/autocarro
* http://conceptnet5.media.mit.edu/web/c/pt/comboio
* http://conceptnet5.media.mit.edu/web/c/pt/chávena

Is there a case where Iberian Portuguese vocabulary is significantly lacking, or not being handled correctly?

**Comment by jarodium** [comment]
Hello

I meant that there is no distinction between Brazilian Portuguese and Portuguese. Although we have a international spelling agreement between Portuguese speak countries, there any some diffferences in the syntax.

Some examples of such differences:

**http://conceptnet5.media.mit.edu/web/c/pt/empresa**

_"conector de rede sem fio  AtLocation  empresa
Um lugar onde você geralmente encontra um(a) conector de rede sem fio é em um(a) empresa."_

the proper way is:
Um lugar onde você geralmente encontra um conector de rede sem fios é numa empresa.

Note here: i don't know why the um(a) is present, but this is due to my lack of understanding ConceptNet 5. My guess that there is no way to distinguish a male/female concept. Conector is a male and empresa is a female ( not gender assuming here :p ) hence 'numa'.

**http://conceptnet5.media.mit.edu/web/c/pt/faxineiro**

_faxineiro  AtLocation  empresa
Um lugar onde você geralmente encontra um(a) faxineiro é em um(a) empresa._

faxineiro is not Iberian for janitor. We have "empregado de limpezas" or "contínuo"

**http://conceptnet5.media.mit.edu/web/c/pt/morango**

_morango  UsedFor  fazer um suco
Um(a) morango é usado(a) para fazer um suco._

we don't use the word suco for juice. We have sumo.

Also as per the new spelling agreement some words will lack a letter which is not spoken, like "acção" is now "ação" and "contracto" is now "contrato", with some exceptions being "facto".

**Comment by jarodium** [comment]
As for my comment about faxineiro, here http://www.priberam.pt/dlpo/faxineiro is a correction for it. In Brazil, they do the same that a janitor does, but in Portugal is a soldier which has the same task of a janitor. Also, my correction for 'faxineiro' is incomplete in the 'contínuo' term. They take care of cleaning in a school, but also perform other task as administration and teacher support as well as student surveillance ( at school, of course ).

**Comment by rspeer** [comment]
> we don't use the word suco for juice. We have sumo.

That's there too: http://conceptnet5.media.mit.edu/web/c/pt/sumo

I don't understand what you'd be doing with ConceptNet where you need to deliberately *not* recognize the word "suco".

If Brazilian and Iberian Portuguese were separated under different language codes, which you might be suggesting, then it looks like instead of 332386 words of unified Portuguese, we would have 332361 words of Brazilian Portuguese and 25 words of Iberian Portuguese (the ones that are specifically marked as such in Wiktionary).

I believe that Iberian Portuguese significantly *benefits* from having the same language code as Brazilian Portuguese: you can get the benefit of all the Portuguese in general that was entered and curated by Brazilians, plus some specific entries for Iberian Portuguese, as long as you don't see it as some kind of error to also recognize Brazilian vocabulary.

Now, about the text that appears under some assertions when you browse to them:

When an assertion comes with a complete sentence of text, such as *Um lugar onde você geralmente encontra um(a) conector de rede sem fio é em um(a) empresa*, this generally indicates that it came from Open Mind Common Sense.

This means someone came to the OMCS do Brasil site, and saw a sentence frame like this (with text boxes):

    Um lugar onde você geralmente encontra um(a) ________ sem fio é em um(a) ________

and they filled in the sentence. It said `um(a)` because the site didn't know the gender of what people will fill in.

The sentence isn't important to the structure of ConceptNet. It's just there to keep track of where the data came from. The fact that the site was "OMCS do Brasil" should indicate why all these sentences are in Brazilian Portuguese.

**Comment by jarodium** [comment]
I would be using the ConceptNet with [SuperScript](http://superscriptjs.com/), a new tool for writing chatbots, since I am beginning to check that type of UI to power a proof of concept for e-commerce.

If the sentence is not important to the structure is a relief, since I thought somehow it was related to how the chatbot would interpret a similar sentence and tell my users that it does not understand Portuguese.

Thank you for clearing me on this.
Best regards
Pedro

**Comment by rspeer** [comment]
I understand.

I would not recommend using ConceptNet to *generate* text in any language, incidentally. You need something else for that -- something that either explicitly or implicitly understands grammar rules, has a model of how to stay on topic, and so on. ConceptNet is mostly designed to be able to *recognize* what text is about.

**Comment by jarodium** [comment]
I think that's the way SuperScript works.
We define a topic, let us say a grocery. A user goes to the website and ask the bot:

- How much is a watermelon?

The bot should be able to understand the 'how much' is the price and the 'watermelon' is the product. Given these two the bot can infer ( of course we still need to provide these model sentences ) , it is supposed to trigger a search for a price for watermelons.

I think it uses the ConceptNet 5 for this kind of recognition.
But I was worried about the bot not understanding Iberian Portuguese, because it's common North Americans relate Portuguese language with Brazilian Portuguese and I have had my past share of having software in my computer using the BR thesaurus for its auto correction features...
