### ISSUE TITLE
types of queries.

### ISSUE THREAD

**Issue by 0985057576qr** [commonsense/conceptnet5#68]
Good afternoon. please tell me any other means of queries to your server is? (except url)
for example in order to be able to analyze the whole sentence or text. (if that is possible)

I apologize in advance for any incorrect translation.

**Comment by rspeer** [comment]
This is part of the product that Luminoso (http://luminoso.com) offers, to analyze domain-specific text with ConceptNet as a starting point. Depending what you're using this for -- is this a project for a company, with a budget for machine learning? -- I could recommend signing up for Luminoso.

Otherwise, there are free NLP tools out there that you could use to segment text into words and phrases and look them up in ConceptNet.
