### ISSUE TITLE
node  structure miss used?

### ISSUE THREAD

**Issue by zhouhoo** [commonsense/conceptnet5#76]
Hi, When I look at the lookup response json data, I found the 'label' in 'start' or 'end' is confusing. Why it is not the same as 'term'?  I found that it is the same as opposite node 'term'.  what's  the label meaning? I can not find the defination throught the source codes. 

` "end": {
        "@id": "/c/zh/馬廄",
        "label": "馬",
        "language": "zh",
        "term": "/c/zh/馬廄"
      },`

**Comment by rspeer** [comment]
You found a bug, thanks.

The label was supposed to be the natural language form of the "term", but we used to only keep track of the natural language form of the entire sentence (`surfaceText`), so we needed to look through `surfaceText` to find the labels. But it looks like it gets the wrong result when one label is a substring of the other.

**Comment by rspeer** [comment]
Actually, this turns out to be unrelated to substrings. It's related to the problem of the reversed frames: when the 'start' and 'end' strings are filled in to the surface text, it loses the order of which was `{1}` and which was `{2}`, so frames where `{2}` comes before `{1}' are supposed to be marked with `*`. This wasn't happening. I've made a branch that fixes the `ptt_petgame.py` reader to add the asterisk to frames when necessary.

**Comment by zhouhoo** [comment]
Ah, thank you. please tell me which name the fixed branch is?

**Comment by rspeer** [comment]
I'm making a branch called `chinese-fixes-5.5`, but I wouldn't consider it done, because I still need to find all the frames that actually have `{1}` and `{2}` in the wrong places.

If you could help me find those, or confirm that the ones you fixed in your pull request were the only problems, it would save me a lot of time using Google Translate.

**Comment by zhouhoo** [comment]
The mapping order in zh_frame.json is correct  from Chinese sentence meaning view.  I built db locally and the data in db looks fine. So I am wonder why data got from your server api look in wrong place.

**Comment by rspeer** [comment]
The swapped labels are fixed now in version 5.5.2.
