### ISSUE TITLE
Issue running python api

### ISSUE THREAD

**Issue by EnricoBeltramo** [commonsense/conceptnet5#85]
Hello,
I tried to install a local copy of conceptnet (using docker) and when I use the API I have this error:

Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from conceptnet5.db.query import AssertionFinder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "conceptnet5/db/query.py", line 1, in <module>
    from .connection import get_db_connection
  File "conceptnet5/db/connection.py", line 35
    file=sys.stderr
        ^
SyntaxError: invalid syntax

Somebody can help me about this issue?

**Comment by rspeer** [comment]
What did you do with Docker?

The error you're showing is an error that results from running Python 3 code in Python 2. This is very strange, as Python 2 is not installed in the Docker container.

**Comment by EnricoBeltramo** [comment]
Thank you for answer,
may be my problem is I'm not usual to docker and posgree. Just to recap:
- I build the docker image
- I started the docker container using: docker-compose start
- I see doker image and all three volumes up. The webinterface works fine.
Now, I would to surf the database using my python application (my previous error was because I used the default 2.7 python instead 3.4), but I have follow error in my application:

erber@erber-VirtualBox:~/conceptnet5$ python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from conceptnet5.db.query import AssertionFinder
>>> cnfinder = AssertionFinder()
>>> cnfinder.lookup('/c/en/example')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/erber/conceptnet5/conceptnet5/db/query.py", line 103, in lookup
    self.connection = get_db_connection(self.dbname)
  File "/home/erber/conceptnet5/conceptnet5/db/connection.py", line 20, in get_db_connection
    raise IOError("The ConceptNet database has not been built.")
OSError: The ConceptNet database has not been built.

I suppose the error is because the conceptnet api don't see the database volume emulated in docker. What I have to do in order to use docker image from host pc api?

Thank you

**Comment by rspeer** [comment]
Ah. `AssertionFinder` is the Python code that directly accesses the database, which I don't refer to as the API. It can't find the database because the database is inside the container.

The API runs over HTTP, and it's the interface that the container exposes. To access this API:

* Configure your `/etc/hosts` so that "api.localhost" refers to 127.0.0.1. (In the next version, I'm making the API server the default host, so this won't be necessary.)
* Access the API via the URLs at https://github.com/commonsense/conceptnet5/wiki/API, except replace `api.conceptnet.io` with `api.localhost`.

For example:

    curl http://api.localhost/c/en/example

If you want to interact with the Python code, then you should build ConceptNet in your Python 3 environment without Docker, as described at https://github.com/commonsense/conceptnet5/wiki/Build-process . I ask people to try Docker first because it takes care of dependencies for you.

By the way, to talk about code or output on GitHub, you should surround it with triple-backticks so that it keeps the formatting:

    ```
    Your code goes here
    ```

**Comment by rspeer** [comment]
The key part there is the MemoryError.

How many GB of RAM do you have available? If it's around 16 GB, then the ConceptNet 5.5.4 update I just pushed will help you -- it should do more to avoid running multiple memory-hungry processes at the same time. Running `pip3 install --upgrade snakemake` may also help, as older versions of Snakemake were ignoring those instructions.

If it's less than 16 GB, there's no hope of being able to build the vectors; sorry. The right plan may be to disable that part of the build and just use precomputed vectors.

**Comment by mrmechko** [comment]
Just leaving my docker workaround here in case it helps someone:

I exposed api.localhost on port 1337 for easy access to the api running within docker and the db on port 5432.  With a small modification to the python code and a few environment variables, I can run the native python api while running conceptnet5 in docker.  I took this approach because I'm running on OS X and many of the dependencies for the system require manual configuration which seemed unnecessary.  Haven't run into any performance issues as of yet.

modified code is at https://github.com/mrmechko/conceptnet5/tree/version5.5

**Comment by rspeer** [comment]
Nice. I think I would like to incorporate something like that. All I'd really need to do is move the port numbers to higher numbers that aren't likely to be contentious.

To be clear: when you set it up this way, you can use modules like `conceptnet5.db.query` outside of Docker, and have them use the DB that was built inside Docker, right?

**Comment by EnricoBeltramo** [comment]
Thank you, looks to be a good solution: I will try immediately
In the while, because my PC looks not to be enough powerful to make all the build I did a little workaround: I copied the full database and files from docker volumes in my local pc. In this way, now the api works fine. Unfortunately they are still a bit too slow for my use. Just there are a list of available commands and argument for the api? I took a look in the wiki, but I find only commands for webapi.

Greets,

**Comment by rspeer** [comment]
As I was saying before, `conceptnet5.db.query` isn't really an API, it's just a part of the ConceptNet code. I didn't design it as a well-specified thing for other people to use. If I significantly change the underlying ConceptNet database, my aim will be to keep the Web API the same as much as possible, even though the entirety of `conceptnet.db` might change, as it did in 5.2, 5.3, and 5.4.

What is the code doing for you that the API wasn't?

**Comment by mrmechko** [comment]
@rspeer that's exactly right.  I can now use `conceptnet5.db.query` from outside Docker.  Initially I actually couldn't figure out how to expose the web api through Docker (new to this stuff).  I don't think it provides anything that the web api itself doesn't.  

One small thing I've noticed is that there doesn't seem to be any pagination directly from python (or maybe I haven't inspected any large enough queries).

**Comment by EnricoBeltramo** [comment]
@rspeer Sure: the web interface is fully complete. My question was only because I noticed that the queries are very slow on my PC and I figured that using directly the api I should have a little improvement of speed. Anyway I'm already inspecting the api in order to understand all the dababase relations. 
Thank you very much for your support!

**Comment by rspeer** [comment]
I'd like to emphasize once again that `conceptnet5.db.query` is not an API, but I can see there are reasons why the Docker container should make the DB available on some port outside the container, so I'll implement that suggestion in a later release.
